### ISSUE TITLE
Huh

### ISSUE THREAD

**Issue by darkdarcool** [PyScript-Language/PyScript-TextEditor#1]
This is cool, but what is this is? 

Also nice team to organize this stuff

**Comment by iop3** [comment]
lmfao yeah

**Comment by kokonut27** [comment]
A text editor that functions and shows code intellegence for pyscript lol. I'll create more info on docs and readme.

Thanks! xD

**Comment by darkdarcool** [comment]
Ah ok. Will it run or will it give you the file to run?

**Comment by kokonut27** [comment]
Idk yet, but i think maybe run

**Comment by darkdarcool** [comment]
Oh ok cool

**Comment by kokonut27** [comment]
> ~~:0 super fast comment~~

**Comment by darkdarcool** [comment]
Yas
